import { StyleSheet } from 'react-native';
import {
  colors,
  fontSize,
  fontWeight,
  layout,
  lineHeight,
  radii,
  spacing,
} from '../../ui/theme';

export const styles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: colors.background },
  container: {
    width: '100%',
    maxWidth: layout.discoveryWidth,
    alignSelf: 'center',
    padding: spacing.xl,
    paddingBottom: spacing.bottom,
    gap: spacing.xl,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.md,
    flexWrap: 'wrap',
  },
  mark: {
    backgroundColor: colors.primary,
    width: layout.brandMark,
    height: layout.brandMark,
    borderRadius: radii.image,
    alignItems: 'center',
    justifyContent: 'center',
  },
  markText: {
    color: colors.white,
    fontSize: fontSize.brandMark,
    fontWeight: fontWeight.heavy,
  },
  wordmark: {
    fontSize: fontSize.wordmark,
    fontWeight: fontWeight.bold,
    color: colors.text,
  },
  small: {
    fontSize: fontSize.badge,
    color: colors.muted,
    letterSpacing: spacing.hairline,
    lineHeight: lineHeight.caption,
  },
  preview: {
    marginLeft: 'auto',
    backgroundColor: colors.border,
    padding: spacing.sm,
    borderRadius: radii.card,
  },
  previewText: {
    fontSize: fontSize.micro,
    letterSpacing: spacing.tracking,
    color: colors.muted,
    fontWeight: fontWeight.bold,
  },
  roles: {
    flexDirection: 'row',
    padding: spacing.xs,
    borderRadius: radii.image,
    backgroundColor: colors.notice,
  },
  role: {
    flex: 1,
    padding: spacing.choice,
    alignItems: 'center',
    borderRadius: radii.small,
  },
  roleActive: { backgroundColor: colors.primary },
  roleText: { fontWeight: fontWeight.semibold, color: colors.muted },
  roleTextActive: { color: colors.white },
  hero: { paddingVertical: spacing.control, gap: spacing.card },
  eyebrow: {
    fontSize: fontSize.tiny,
    letterSpacing: spacing.tiny,
    color: colors.accent,
    fontWeight: fontWeight.bold,
  },
  title: {
    fontSize: fontSize.discoveryTitle,
    lineHeight: lineHeight.discoveryTitle,
    letterSpacing: spacing.titleTracking,
    fontWeight: fontWeight.bold,
    color: colors.text,
  },
  intro: {
    fontSize: fontSize.input,
    lineHeight: lineHeight.intro,
    color: colors.muted,
  },
  tags: { flexDirection: 'row', gap: spacing.sm, flexWrap: 'wrap' },
  tag: {
    fontSize: fontSize.badge,
    color: colors.accent,
    backgroundColor: colors.secondary,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.tag,
    borderRadius: radii.card,
  },
  sectionHeader: { flexDirection: 'row', justifyContent: 'space-between' },
  sectionTitle: {
    fontSize: fontSize.heading,
    color: colors.text,
    fontWeight: fontWeight.semibold,
  },
  filters: { flexDirection: 'row', gap: spacing.sm, marginTop: -spacing.row },
  filter: {
    paddingVertical: spacing.md,
    paddingHorizontal: spacing.card,
    borderRadius: radii.panel,
    borderWidth: 1,
    borderColor: colors.border,
  },
  filterActive: { backgroundColor: colors.text, borderColor: colors.text },
  filterText: { color: colors.muted, fontWeight: fontWeight.medium },
  filterTextActive: { color: colors.white },
  empty: {
    padding: spacing.empty,
    gap: spacing.lg,
    alignItems: 'center',
    backgroundColor: colors.surface,
    borderRadius: radii.panel,
    borderWidth: 1,
    borderColor: colors.border,
  },
  emptySymbol: { fontSize: fontSize.discoveryTitle, color: colors.accent },
  emptyTitle: {
    fontSize: fontSize.section,
    color: colors.text,
    fontWeight: fontWeight.semibold,
    textAlign: 'center',
  },
  body: {
    color: colors.muted,
    fontSize: fontSize.label,
    lineHeight: lineHeight.notice,
  },
  button: {
    backgroundColor: colors.primary,
    paddingHorizontal: spacing.xl,
    paddingVertical: spacing.control,
    borderRadius: radii.control,
  },
  buttonText: { color: colors.white, fontWeight: fontWeight.semibold },
  card: {
    backgroundColor: colors.surface,
    borderRadius: radii.panel,
    padding: spacing.xl,
    gap: spacing.lg,
    borderWidth: 1,
    borderColor: colors.border,
  },
  price: {
    color: colors.primary,
    fontSize: fontSize.subtitle,
    fontWeight: fontWeight.bold,
  },
  note: {
    fontSize: fontSize.caption,
    lineHeight: lineHeight.caption,
    color: colors.muted,
    marginTop: spacing.small,
  },
  how: { gap: spacing.steps, paddingTop: spacing.md },
  step: { flexDirection: 'row', gap: spacing.card },
  stepNumber: {
    color: colors.accent,
    fontSize: fontSize.compact,
    fontWeight: fontWeight.bold,
    paddingTop: spacing.xs,
  },
  stepContent: { flex: 1, gap: spacing.xxs },
  stepTitle: {
    fontSize: fontSize.input,
    fontWeight: fontWeight.semibold,
    color: colors.text,
  },
  footer: {
    color: colors.muted,
    fontSize: fontSize.micro,
    letterSpacing: spacing.trackingWide,
    textAlign: 'center',
    paddingTop: spacing.section,
  },
});
