import { StyleSheet } from 'react-native';
import {
  colors,
  fontSize,
  fontWeight,
  layout,
  lineHeight,
  radii,
  spacing,
} from './theme';

export const ui = StyleSheet.create({
  fill: { flex: 1 },
  multiline: { minHeight: layout.multilineHeight, textAlignVertical: 'top' },
  safe: { flex: 1, backgroundColor: colors.background },
  page: {
    width: '100%',
    maxWidth: layout.pageWidth,
    alignSelf: 'center',
    padding: spacing.xl,
    paddingBottom: spacing.pageBottom,
    gap: spacing.lg,
  },
  wordmark: {
    fontSize: fontSize.caption,
    letterSpacing: spacing.tiny,
    color: colors.accent,
    fontWeight: fontWeight.bold,
    marginVertical: spacing.sm,
  },
  title: {
    fontSize: fontSize.title,
    lineHeight: lineHeight.title,
    fontWeight: fontWeight.bold,
    color: colors.text,
  },
  body: {
    fontSize: fontSize.body,
    lineHeight: lineHeight.body,
    color: colors.muted,
  },
  field: { gap: spacing.sm },
  label: {
    fontSize: fontSize.label,
    fontWeight: fontWeight.semibold,
    color: colors.text,
  },
  input: {
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surface,
    borderRadius: radii.small,
    padding: spacing.input,
    fontSize: fontSize.input,
    color: colors.text,
  },
  error: { color: colors.danger, lineHeight: lineHeight.error },
  notice: {
    backgroundColor: colors.notice,
    padding: spacing.control,
    borderRadius: radii.small,
    color: colors.primary,
    lineHeight: lineHeight.notice,
  },
  row: { flexDirection: 'row', gap: spacing.row },
  chip: {
    borderWidth: 1,
    borderColor: colors.border,
    padding: spacing.sm,
    borderRadius: radii.control,
    flex: 1,
    alignItems: 'center',
  },
  choiceLabel: {
    fontSize: fontSize.caption,
    color: colors.text,
    fontWeight: fontWeight.semibold,
    textAlign: 'center',
  },
  selected: { backgroundColor: colors.selected, borderColor: colors.primary },
});
